language: node_js
node_js:
  - 0.10
before_install:
  - npm install -g grunt-cli
  - npm install grunt-contrib-jasmine --save-dev
deploy:
  provider: heroku
  api_key: 8adab5cab768a0df58cd6276ee0db2bae927064e
  strategy: git